services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
    volumes:
      - /data/grafana:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      bridge:
        ipv4_address: 172.28.0.10

networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
